update : responses.json & responses_th.json
Celestial-Project/Celestial-Legacy pull request #11
Opened 2022-07-08 14:53 UTC by Peachpiggies

add
- "number"
- "number_th"

in responses.json & responses_th.json

2022-07-10 13:04 UTC, StrixzIV requested changes

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses.json
> +    "list_of_words": ["do","you","have","siblings"],
Maybe remove "do" and "you". 
This will reduce the lookup time of the engine.

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses_th.json
> +    "list_of_words": ["มี","เบอร์","โทร","ไหม"],
Remove "ไหม" here too.

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses.json
> +    "list_of_words": ["can","i","have","your","number"],
I think you should remove the "I"

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses_th.json
> +    "list_of_words": ["มี","พี่น้อง","ไหม"],
Remove "ไหม"

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses.json
> +      "Um... I don't know about that dad didn't tell me about that at all."
I think this should be "Um... I don't know about that much... My dad didn't tell me about that. Maybe one day I'll ask him."

2022-07-10 13:04 UTC, StrixzIV commented on responses/responses.json
> +      "Um... I don't know about that dad didn't tell me about that at all."
And also, I think of you can make more responses here, this would be better.

2022-07-11 00:44 UTC, StrixzIV approved these changes
Approve!

2022-07-11 00:44 UTC, merged

2022-07-11 00:46 UTC, Peachpiggies commented
Thanks