festival.json : valentine update both en & th
Celestial-Project/Celestial-Legacy pull request #36
Opened 2023-02-12 22:23 UTC by Peachpiggies

2023-02-13 03:31 UTC, StrixzIV requested changes
Fix the date pls

2023-02-13 03:31 UTC, StrixzIV commented on responses/festivals.json
> +        "date": [14],
This data is an integer data so change this to `"date: 14"`

2023-02-13 03:31 UTC, StrixzIV commented on responses/festivals_th.json
> +        "date": [14],
This data is an integer data so change this to `"date: 14"`

2023-02-14 12:29 UTC, Peachpiggies reviewed
This will do it now.

2023-02-14 12:30 UTC, Peachpiggies reviewed
This will do it right.
:3

2023-02-14 12:31 UTC, StrixzIV approved these changes

2023-02-14 12:31 UTC, merged